repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.6
    hooks:
      - id: uv-lock
      - id: uv-sync
      - id: uv-export
        args: ["--frozen", "--output-file=requirements.txt", "--quiet"]
