# Project information
site_name: Moon Wiki
site_url: https://lifeadventurer.github.io/wiki/
site_author: LifeAdventurer <life0adventurer@gmail.com>
site_description: A lovely place

# Repository
repo_name: LifeAdventurer/wiki
repo_url: https://github.com/LifeAdventurer/wiki/

# Copyright
copyright: Copyright &copy; 2024 LifeAdventurer

# Configuration
theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material//weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: indigo
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.expand
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow

# Plugins
plugins:
  - blog
  - search

# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LifeAdventurer

# Page tree
nav:
  - Home: index.md
  - Portfolio:
    - Portfolio Overview: portfolio/index.md
  - Blog:
    - blog/index.md
